services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork
      - prisma-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork

  app:
    image: node:latest
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/mydatabase?schema=public"
    volumes:
      - .:/app
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npm run build &&
             npm run start:prod"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  prisma-studio:
    image: node:latest
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/mydatabase?schema=public"
    command: npx prisma studio
    depends_on:
      - postgres
    ports:
      - "5555:5555"
    networks:
      - prisma-network

networks:
  mynetwork:
    driver: bridge
  prisma-network:
    driver: bridge

volumes:
  pgdata:
